# Generated by Django 6.0.7 on 2026-08-02 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('disciplina', 'Disciplina'), ('modulo', 'Módulo'), ('seminario', 'Seminário de Integração'), ('atividade', 'Atividade Orientada')], max_length=20)),
                ('natureza', models.CharField(choices=[('obrigatoria', 'Obrigatória'), ('optativa', 'Optativa')], max_length=20)),
                ('nucleo', models.CharField(choices=[('NC', 'Núcleo Comum'), ('NE', 'Núcleo Específico'), ('NL', 'Núcleo Livre'), ('AC', 'Atividade Complementar'), ('ACEx', 'Atividade Curricular de Extensão')], max_length=4)),
                ('periodo', models.PositiveSmallIntegerField()),
                ('carga_horaria_teorica', models.PositiveIntegerField()),
                ('carga_horaria_pratica', models.PositiveIntegerField()),
                ('carga_horaria_pcc', models.PositiveIntegerField(default=0, help_text='Horas de Prática como Componente Curricular (só licenciaturas)')),
                ('unidade_academica_componente', models.CharField(max_length=200)),
                ('ementa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('unidade_academica', models.CharField(max_length=200)),
                ('area_conhecimento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('basica', 'Básica'), ('complementar', 'Complementar')], max_length=15)),
                ('titulo', models.CharField(max_length=300)),
                ('autores', models.CharField(max_length=300)),
                ('editora', models.CharField(blank=True, max_length=150)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliografias', to='ppc.componentecurricular')),
            ],
        ),
        migrations.CreateModel(
            name='PPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('ead', 'A Distância')], max_length=20)),
                ('grau_academico', models.CharField(choices=[('bacharelado', 'Bacharelado'), ('licenciatura', 'Licenciatura')], max_length=20)),
                ('turno_funcionamento', models.CharField(max_length=50)),
                ('carga_horaria_total', models.PositiveIntegerField(help_text='em horas')),
                ('numero_vagas_anuais', models.PositiveIntegerField()),
                ('duracao_minima_semestres', models.PositiveIntegerField()),
                ('duracao_media_semestres', models.PositiveIntegerField()),
                ('duracao_maxima_semestres', models.PositiveIntegerField()),
                ('diretor', models.CharField(max_length=200)),
                ('vice_diretor', models.CharField(max_length=200)),
                ('coordenador_curso', models.CharField(max_length=200)),
                ('publico_alvo_ead', models.TextField(blank=True)),
                ('ato_integracao_uab', models.CharField(blank=True, max_length=200)),
                ('ato_credenciamento_mec', models.CharField(blank=True, max_length=200)),
                ('polos_ead', models.TextField(blank=True)),
                ('apresentacao_texto', models.TextField()),
                ('tipo_ppc', models.CharField(choices=[('novo', 'Curso Novo'), ('reformulacao', 'Reformulação Curricular')], max_length=20)),
                ('exposicao_motivos', models.TextField()),
                ('objetivo_geral', models.TextField()),
                ('objetivo_especifico', models.TextField()),
                ('principios_geral', models.TextField()),
                ('principios_pratica_profissional', models.TextField()),
                ('principios_formacao_tecnica', models.TextField()),
                ('principios_formacao_etica_social', models.TextField()),
                ('principios_interdisciplinaridade', models.TextField()),
                ('principios_articulacao_teoria_pratica', models.TextField()),
                ('perfil_curso', models.TextField()),
                ('perfil_habilidades', models.TextField()),
                ('tcc', models.TextField()),
                ('estagio', models.TextField()),
                ('atividades_complementares', models.TextField()),
                ('politicas_integrada', models.TextField()),
                ('avaliacao_ensino_aprendigem', models.TextField()),
                ('avaliacao_projeto_curso', models.TextField()),
                ('qualificacao', models.TextField()),
                ('diretrizes_curriculares_nacionais_curso', models.TextField()),
                ('diretrizes_curriculares_nacionais_educacao_basica', models.TextField(blank=True)),
                ('diretrizes_etnico_raciais_historia_cultura_afro_indigena', models.TextField()),
                ('diretrizes_educacao_direitos_humanos', models.TextField()),
                ('protecao_direitos_pessoa_transtorno_espectro_autista', models.TextField()),
                ('componente_curricular_libras', models.TextField()),
                ('politicas_educacao_ambiental', models.TextField()),
                ('diretrizes_formacao_professores_educacao_basica', models.TextField(blank=True)),
                ('condicoes_acesso_pessoas_deficiencia_mobilidade_reduzida', models.TextField()),
                ('bibliografias_ppc', models.TextField()),
                ('estrutura_curricular_descricao', models.TextField()),
                ('estrutura_curricular_informacoes_complementares', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppcs', to='ppc.curso')),
            ],
        ),
        migrations.CreateModel(
            name='DinamicaEAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinamica_atividades_presenciais_distancia', models.TextField(blank=True)),
                ('recuperacao_estudos_permanencia', models.TextField(blank=True)),
                ('componente_informatica_basica', models.TextField(blank=True)),
                ('atuacao_tutoria', models.TextField(blank=True)),
                ('atribuicoes_profissionais', models.TextField(blank=True)),
                ('material_didatico', models.TextField(blank=True)),
                ('ferramentas_comunicacao', models.TextField(blank=True)),
                ('carga_horaria_presencial_acompanhamento', models.TextField(blank=True)),
                ('armazenamento_gerenciamento_dados', models.TextField(blank=True)),
                ('ppc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dinamica_ead', to='ppc.ppc')),
            ],
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='ppc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_curriculares', to='ppc.ppc'),
        ),
        migrations.CreateModel(
            name='Apendice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('corpo_docente', 'Relação do corpo docente e titulação'), ('quadro_oferta', 'Quadro semestral de oferta de componentes curriculares')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, upload_to='apendices/')),
                ('ppc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apendices', to='ppc.ppc')),
            ],
        ),
        migrations.CreateModel(
            name='RelacaoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pre_requisito', 'Pré-requisito'), ('co_requisito', 'Co-requisito'), ('equivalente', 'Equivalente')], max_length=20)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes', to='ppc.componentecurricular')),
                ('componente_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionado_em', to='ppc.componentecurricular')),
            ],
            options={
                'unique_together': {('componente', 'componente_relacionado', 'tipo')},
            },
        ),
    ]
