# Generated by Django 6.0.7 on 2026-08-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CineBrasilCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=255)),
                ('area_geral_codigo', models.CharField(max_length=2)),
                ('area_geral_nome', models.CharField(max_length=255)),
                ('rotulo_codigo', models.CharField(max_length=8)),
                ('rotulo_nome', models.CharField(max_length=255)),
                ('origem', models.CharField(blank=True, choices=[('DCN', 'DCN'), ('CNCST', 'CNCST')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='grau_academico',
            field=models.CharField(choices=[('bacharelado', 'Bacharelado'), ('licenciatura', 'Licenciatura'), ('tecnologo', 'Tecnólogo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='modalidade',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('ead', 'A Distância'), ('semipresencial', 'Semipresencial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='grau_academico',
            field=models.CharField(choices=[('bacharelado', 'Bacharelado'), ('licenciatura', 'Licenciatura'), ('tecnologo', 'Tecnólogo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='modalidade',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('ead', 'A Distância'), ('semipresencial', 'Semipresencial')], max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='cine_brasil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ppc.cinebrasilcurso'),
        ),
        migrations.AddField(
            model_name='historicalcurso',
            name='cine_brasil',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ppc.cinebrasilcurso'),
        ),
    ]
