# Generated by Django 6.0.7 on 2026-08-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0002_cinebrasilcurso_alter_historicalppc_grau_academico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentecurricular',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de aprovação'), ('aprovado', 'Aprovado')], default='aprovado', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcomponentecurricular',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de aprovação'), ('aprovado', 'Aprovado')], default='aprovado', max_length=20),
        ),
    ]
