# Generated by Django 6.0.7 on 2026-08-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0004_historicalapendice_historicalcomponentecurricular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalppc',
            old_name='avaliacao_ensino_aprendigem',
            new_name='avaliacao_ensino_aprendizagem',
        ),
        migrations.RenameField(
            model_name='ppc',
            old_name='avaliacao_ensino_aprendigem',
            new_name='avaliacao_ensino_aprendizagem',
        ),
    ]
