# Generated by Django 6.0.7 on 2026-09-13 18:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0004_componentecurricular_criado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoPendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ambigua', 'Ambígua (núcleo/natureza indeterminados)'), ('duplicada_conflitante', 'Duplicada com dado conflitante'), ('sem_mapeamento', 'Sem mapeamento de curso')], max_length=30)),
                ('identificador_origem', models.CharField(max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('linha_origem', models.PositiveIntegerField(blank=True, null=True)),
                ('detalhe', models.TextField(blank=True, help_text='Motivo da ambiguidade, ou comparação da linha conflitante, conforme o tipo.')),
                ('dados_brutos', models.JSONField(help_text='Linha(s) originais normalizadas, para referência/depuração.')),
                ('resolvido', models.BooleanField(default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pendência de importação',
                'verbose_name_plural': 'Pendências de importação',
                'ordering': ['resolvido', 'tipo', 'linha_origem'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMatrizReferenciaCurricular',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text="Ex: 'Matriz de Referência — Noturno'. Opcional, útil quando há mais de uma por curso.", max_length=200)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('curso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ppc.curso')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical matriz referencia curricular',
                'verbose_name_plural': 'historical matriz referencia curriculars',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MapeamentoImportacaoMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_origem', models.CharField(help_text="Ex: 'FIS-LN-2C', como aparece na coluna matriz_curricular da planilha.", max_length=50, unique=True)),
                ('nome_matriz_referencia', models.CharField(blank=True, help_text="Nome a dar à MatrizReferenciaCurricular criada (ex: 'Noturno'). Opcional.", max_length=200)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppc.curso')),
            ],
        ),
        migrations.CreateModel(
            name='MatrizReferenciaCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text="Ex: 'Matriz de Referência — Noturno'. Opcional, útil quando há mais de uma por curso.", max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrizes_referencia', to='ppc.curso')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalComponenteNaMatrizReferencia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('periodo', models.PositiveSmallIntegerField()),
                ('natureza', models.CharField(choices=[('obrigatoria', 'Obrigatória'), ('optativa', 'Optativa')], max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Posição dentro do período, para uso futuro no drag-and-drop.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('componente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ppc.componentecurricular')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matriz', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ppc.matrizreferenciacurricular')),
            ],
            options={
                'verbose_name': 'historical componente na matriz referencia',
                'verbose_name_plural': 'historical componente na matriz referencias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ComponenteNaMatrizReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveSmallIntegerField()),
                ('natureza', models.CharField(choices=[('obrigatoria', 'Obrigatória'), ('optativa', 'Optativa')], max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Posição dentro do período, para uso futuro no drag-and-drop.')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uso_em_matrizes_referencia', to='ppc.componentecurricular')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='ppc.matrizreferenciacurricular')),
            ],
            options={
                'ordering': ['periodo', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('matriz', 'componente'), name='uniq_componente_matriz_referencia')],
            },
        ),
    ]
