# Generated by Django 6.0.7 on 2026-09-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0005_importacaopendencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapeamentoimportacaomatriz',
            name='curso',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco até identificar a que curso este identificador pertence.', null=True, on_delete=django.db.models.deletion.PROTECT, to='ppc.curso'),
        ),
    ]
