# Generated by Django 6.0.7 on 2026-08-05 19:50

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0005_rename_avaliacao_ensino_aprendigem_historicalppc_avaliacao_ensino_aprendizagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalppc',
            name='atividades_complementares',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Atividades Complementares'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='avaliacao_ensino_aprendizagem',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Avaliação do Processo de Ensino e de Aprendizagem'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='avaliacao_projeto_curso',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Avaliação do Projeto de Curso'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='bibliografias_ppc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Referências'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='componente_curricular_libras',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Componente Curricular de Libras'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='condicoes_acesso_pessoas_deficiencia_mobilidade_reduzida',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Condições de Acesso para Pessoas com Deficiência e/ou Mobilidade Reduzida'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='diretrizes_curriculares_nacionais_curso',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Diretrizes Curriculares Nacionais do Curso'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='diretrizes_curriculares_nacionais_educacao_basica',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Diretrizes Curriculares Nacionais da Educação Básica'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='diretrizes_educacao_direitos_humanos',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Diretrizes Nacionais para a Educação em Direitos Humanos'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='diretrizes_etnico_raciais_historia_cultura_afro_indigena',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Diretrizes para Educação das Relações Étnico-Raciais e Ensino de História e Cultura Afro-Brasileira e Indígena'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='diretrizes_formacao_professores_educacao_basica',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Diretrizes Curriculares Nacionais para a Formação de Professores da Educação Básica'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='estagio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Política e Gestão de Estágio Curricular Obrigatório e Não Obrigatório'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='estrutura_curricular_descricao',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descrição Geral'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='estrutura_curricular_informacoes_complementares',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Informações Complementares'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='exposicao_motivos',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Exposição de Motivos'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='perfil_curso',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Perfil do Curso'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='perfil_habilidades',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Perfil e Habilidades do Egresso'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='politicas_educacao_ambiental',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Políticas de Educação Ambiental'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='politicas_integrada',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Integração Ensino, Pesquisa e Extensão'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='principios_articulacao_teoria_pratica',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Articulação entre Teoria e Prática'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='principios_formacao_etica_social',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Formação Ética e Função Social do Profissional'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='principios_formacao_tecnica',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Formação Técnica'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='principios_geral',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Princípios Gerais'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='principios_interdisciplinaridade',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Interdisciplinaridade'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='principios_pratica_profissional',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Prática Profissional'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='protecao_direitos_pessoa_transtorno_espectro_autista',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Proteção dos Direitos da Pessoa com Transtorno do Espectro Autista'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='qualificacao',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Qualificação de Docentes e Técnico-Administrativos'),
        ),
        migrations.AlterField(
            model_name='historicalppc',
            name='tipo_ppc',
            field=models.CharField(choices=[('novo', 'Curso Novo'), ('reformulacao', 'Reformulação Curricular')], max_length=20, verbose_name='Tipo de PPC'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='atividades_complementares',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Atividades Complementares'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='avaliacao_ensino_aprendizagem',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Avaliação do Processo de Ensino e de Aprendizagem'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='avaliacao_projeto_curso',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Avaliação do Projeto de Curso'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='bibliografias_ppc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Referências'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='componente_curricular_libras',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Componente Curricular de Libras'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='condicoes_acesso_pessoas_deficiencia_mobilidade_reduzida',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Condições de Acesso para Pessoas com Deficiência e/ou Mobilidade Reduzida'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='diretrizes_curriculares_nacionais_curso',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Diretrizes Curriculares Nacionais do Curso'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='diretrizes_curriculares_nacionais_educacao_basica',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Diretrizes Curriculares Nacionais da Educação Básica'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='diretrizes_educacao_direitos_humanos',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Diretrizes Nacionais para a Educação em Direitos Humanos'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='diretrizes_etnico_raciais_historia_cultura_afro_indigena',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Diretrizes para Educação das Relações Étnico-Raciais e Ensino de História e Cultura Afro-Brasileira e Indígena'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='diretrizes_formacao_professores_educacao_basica',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Diretrizes Curriculares Nacionais para a Formação de Professores da Educação Básica'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='estagio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Política e Gestão de Estágio Curricular Obrigatório e Não Obrigatório'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='estrutura_curricular_descricao',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descrição Geral'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='estrutura_curricular_informacoes_complementares',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Informações Complementares'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='exposicao_motivos',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Exposição de Motivos'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='perfil_curso',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Perfil do Curso'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='perfil_habilidades',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Perfil e Habilidades do Egresso'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='politicas_educacao_ambiental',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Políticas de Educação Ambiental'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='politicas_integrada',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Integração Ensino, Pesquisa e Extensão'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='principios_articulacao_teoria_pratica',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Articulação entre Teoria e Prática'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='principios_formacao_etica_social',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Formação Ética e Função Social do Profissional'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='principios_formacao_tecnica',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Formação Técnica'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='principios_geral',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Princípios Gerais'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='principios_interdisciplinaridade',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Interdisciplinaridade'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='principios_pratica_profissional',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Prática Profissional'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='protecao_direitos_pessoa_transtorno_espectro_autista',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Proteção dos Direitos da Pessoa com Transtorno do Espectro Autista'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='qualificacao',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Qualificação de Docentes e Técnico-Administrativos'),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='tipo_ppc',
            field=models.CharField(choices=[('novo', 'Curso Novo'), ('reformulacao', 'Reformulação Curricular')], max_length=20, verbose_name='Tipo de PPC'),
        ),
        migrations.CreateModel(
            name='MembroNDE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('titulacao', models.CharField(choices=[('doutor', 'Doutor(a)'), ('mestre', 'Mestre'), ('especialista', 'Especialista'), ('graduado', 'Graduado(a)')], max_length=20, verbose_name='Titulação')),
                ('regime_trabalho', models.CharField(choices=[('de', 'Dedicação Exclusiva'), ('40h', '40 horas'), ('20h', '20 horas')], max_length=10, verbose_name='Regime de Trabalho')),
                ('funcao', models.CharField(choices=[('presidente', 'Presidente/Coordenador(a) do NDE'), ('membro', 'Membro')], default='membro', max_length=20, verbose_name='Função no Núcleo')),
                ('portaria_designacao', models.CharField(blank=True, max_length=200, verbose_name='Portaria/Ato de Designação')),
                ('data_inicio', models.DateField(verbose_name='Data de Início no Núcleo')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Saída (se aplicável)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no Núcleo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_nde', to='ppc.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Membro do NDE',
                'verbose_name_plural': 'Membros do NDE',
            },
        ),
    ]
