# Generated by Django 6.0.7 on 2026-09-14 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0006_alter_mapeamentoimportacaomatriz_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatrizreferenciacurricular',
            name='identificador_origem',
            field=models.CharField(blank=True, db_index=True, help_text="Identificador original da planilha (ex: 'FIS-LN-2C'), para rastreio antes/depois de vincular a um Curso.", max_length=50),
        ),
        migrations.AddField(
            model_name='matrizreferenciacurricular',
            name='identificador_origem',
            field=models.CharField(blank=True, help_text="Identificador original da planilha (ex: 'FIS-LN-2C'), para rastreio antes/depois de vincular a um Curso.", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalmatrizreferenciacurricular',
            name='curso',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Pode ficar em branco até alguém identificar a que curso esta matriz pertence.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ppc.curso'),
        ),
        migrations.AlterField(
            model_name='historicalmatrizreferenciacurricular',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='matrizreferenciacurricular',
            name='curso',
            field=models.ForeignKey(blank=True, help_text='Pode ficar em branco até alguém identificar a que curso esta matriz pertence.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matrizes_referencia', to='ppc.curso'),
        ),
        migrations.AlterField(
            model_name='matrizreferenciacurricular',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
