# Generated by Django 6.0.7 on 2026-08-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0006_alter_historicalppc_atividades_complementares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalppc',
            name='numero_resolucao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número da Resolução de Aprovação'),
        ),
        migrations.AddField(
            model_name='ppc',
            name='numero_resolucao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número da Resolução de Aprovação'),
        ),
    ]
