# Generated by Django 6.0.7 on 2026-08-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0007_historicalppc_numero_resolucao_ppc_numero_resolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentecurricular',
            name='carga_horaria_acex',
            field=models.PositiveIntegerField(blank=True, help_text='Atividade Curricular de Extensão (núcleo ACEx): carga horária total do componente.', null=True),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='carga_horaria_estudante',
            field=models.PositiveIntegerField(blank=True, help_text='Atividade Orientada: carga horária máxima prevista para o estudante.', null=True),
        ),
        migrations.AddField(
            model_name='componentecurricular',
            name='carga_horaria_professor',
            field=models.PositiveIntegerField(blank=True, help_text='Atividade Orientada: carga horária do professor — deve ser menor ou igual à do estudante.', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='carga_horaria_maxima',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='carga_horaria_minima',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentecurricular',
            name='carga_horaria_acex',
            field=models.PositiveIntegerField(blank=True, help_text='Atividade Curricular de Extensão (núcleo ACEx): carga horária total do componente.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentecurricular',
            name='carga_horaria_estudante',
            field=models.PositiveIntegerField(blank=True, help_text='Atividade Orientada: carga horária máxima prevista para o estudante.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentecurricular',
            name='carga_horaria_professor',
            field=models.PositiveIntegerField(blank=True, help_text='Atividade Orientada: carga horária do professor — deve ser menor ou igual à do estudante.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcurso',
            name='carga_horaria_maxima',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcurso',
            name='carga_horaria_minima',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
