# Generated by Django 6.0.7 on 2026-09-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0007_historicalmatrizreferenciacurricular_identificador_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatrizreferenciacurricular',
            name='numero_periodos',
            field=models.PositiveSmallIntegerField(default=12, help_text='Quantidade de períodos exibidos na tela de edição desta matriz.'),
        ),
        migrations.AddField(
            model_name='matrizreferenciacurricular',
            name='numero_periodos',
            field=models.PositiveSmallIntegerField(default=12, help_text='Quantidade de períodos exibidos na tela de edição desta matriz.'),
        ),
    ]
