# Generated by Django 6.0.7 on 2026-09-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0008_historicalmatrizreferenciacurricular_numero_periodos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentecurricular',
            name='unidade_academica_componente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalcomponentecurricular',
            name='unidade_academica_componente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalmatrizreferenciacurricular',
            name='identificador_origem',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="Identificador original da planilha (ex: 'FIS-LN-2C'), para rastreio antes/depois de vincular a um Curso.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matrizreferenciacurricular',
            name='identificador_origem',
            field=models.CharField(blank=True, default=None, help_text="Identificador original da planilha (ex: 'FIS-LN-2C'), para rastreio antes/depois de vincular a um Curso.", max_length=50, null=True, unique=True),
        ),
    ]
