# Generated by Django 6.0.7 on 2026-09-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0009_alter_componentecurricular_unidade_academica_componente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalppc',
            name='vice_coordenador_curso',
            field=models.CharField(default='A definir', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppc',
            name='vice_coordenador_curso',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
