# Generated by Django 6.0.7 on 2026-09-22 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0010_historicalppc_vice_coordenador_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliografiaReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('basica', 'Básica'), ('complementar', 'Complementar')], max_length=15)),
                ('titulo', models.CharField(max_length=300)),
                ('autores', models.CharField(max_length=300)),
                ('editora', models.CharField(blank=True, max_length=150)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('componente_na_matriz_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliografias', to='ppc.componentenamatrizreferencia')),
            ],
        ),
    ]
