# Generated by Django 6.0.7 on 2026-09-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0012_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='resolvido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('resolvido', 'Resolvido')], default='pendente', max_length=20),
        ),
    ]
