# Generated by Django 6.0.7 on 2026-10-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0013_chamado_resolvido_em_chamado_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentecurricular',
            name='nucleo',
        ),
        migrations.RemoveField(
            model_name='historicalcomponentecurricular',
            name='nucleo',
        ),
        migrations.AddField(
            model_name='componentenamatriz',
            name='nucleo',
            field=models.CharField(choices=[('NC', 'Núcleo Comum'), ('NE', 'Núcleo Específico')], default='NE', max_length=4),
        ),
        migrations.AddField(
            model_name='componentenamatrizreferencia',
            name='nucleo',
            field=models.CharField(choices=[('NC', 'Núcleo Comum'), ('NE', 'Núcleo Específico')], default='NE', max_length=4),
        ),
        migrations.AddField(
            model_name='historicalcomponentenamatriz',
            name='nucleo',
            field=models.CharField(choices=[('NC', 'Núcleo Comum'), ('NE', 'Núcleo Específico')], default='NE', max_length=4),
        ),
        migrations.AddField(
            model_name='historicalcomponentenamatrizreferencia',
            name='nucleo',
            field=models.CharField(choices=[('NC', 'Núcleo Comum'), ('NE', 'Núcleo Específico')], default='NE', max_length=4),
        ),
        migrations.AlterField(
            model_name='historicalrelacaocomponente',
            name='tipo',
            field=models.CharField(choices=[('pre_requisito', 'Pré-requisito'), ('co_requisito', 'Co-requisito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='relacaocomponente',
            name='tipo',
            field=models.CharField(choices=[('pre_requisito', 'Pré-requisito'), ('co_requisito', 'Co-requisito')], max_length=20),
        ),
    ]
