# Generated by Django 6.0.7 on 2026-10-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0014_remove_componentecurricular_nucleo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmatrizreferenciacurricular',
            name='numero_periodos',
            field=models.PositiveSmallIntegerField(default=8, help_text='Quantidade de períodos exibidos na tela de edição desta matriz.'),
        ),
        migrations.AlterField(
            model_name='matrizreferenciacurricular',
            name='numero_periodos',
            field=models.PositiveSmallIntegerField(default=8, help_text='Quantidade de períodos exibidos na tela de edição desta matriz.'),
        ),
    ]
