# Generated by Django 6.0.7 on 2026-10-08 04:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0015_alter_historicalmatrizreferenciacurricular_numero_periodos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEquivalenciaComponentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('matriz_final', models.ForeignKey(blank=True, help_text='Matriz a ser considerada vigente quando a resolução for publicada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_como_matriz_final', to='ppc.matrizreferenciacurricular')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalGrupoEquivalenciaComponentes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matriz_final', models.ForeignKey(blank=True, db_constraint=False, help_text='Matriz a ser considerada vigente quando a resolução for publicada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ppc.matrizreferenciacurricular')),
            ],
            options={
                'verbose_name': 'historical grupo equivalencia componentes',
                'verbose_name_plural': 'historical grupo equivalencia componentess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalResumoCargaHorariaPPC',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nucleo_livre_manual', models.PositiveIntegerField(default=0)),
                ('acex_nucleo_livre_manual', models.PositiveIntegerField(default=0)),
                ('acex_extensao_manual', models.PositiveIntegerField(default=0)),
                ('atividades_complementares_manual', models.PositiveIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ppc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ppc.ppc')),
            ],
            options={
                'verbose_name': 'historical resumo carga horaria ppc',
                'verbose_name_plural': 'historical resumo carga horaria ppcs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ResumoCargaHorariaPPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nucleo_livre_manual', models.PositiveIntegerField(default=0)),
                ('acex_nucleo_livre_manual', models.PositiveIntegerField(default=0)),
                ('acex_extensao_manual', models.PositiveIntegerField(default=0)),
                ('atividades_complementares_manual', models.PositiveIntegerField(default=0)),
                ('ppc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumo_carga_horaria', to='ppc.ppc')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEquivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ppc.grupoequivalenciacomponentes')),
                ('item_matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias', to='ppc.componentenamatrizreferencia')),
            ],
            options={
                'unique_together': {('grupo', 'item_matriz')},
            },
        ),
    ]
