# Generated by Django 6.0.7 on 2026-10-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0016_grupoequivalenciacomponentes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemequivalencia',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='itemequivalencia',
            name='ordem',
            field=models.PositiveIntegerField(default=1, help_text='Posição da matriz na sequência (a de maior ordem é a que será cadastrada na Resolução)'),
        ),
    ]
