# Generated by Django 6.0.7 on 2026-10-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0017_alter_itemequivalencia_options_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='componentecurricular',
            name='ccu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomponentecurricular',
            name='ccu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalppc',
            name='ano_vigencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalppc',
            name='coordenador_administrativo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalppc',
            name='data_aprovacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalppc',
            name='data_resolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalppc',
            name='numero_processo_eletronico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número do processo eletrônico'),
        ),
        migrations.AddField(
            model_name='historicalppc',
            name='reitor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalppc',
            name='semestre_vigencia',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
        migrations.AddField(
            model_name='historicalppc',
            name='vice_reitor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ppc',
            name='ano_vigencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppc',
            name='coordenador_administrativo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ppc',
            name='data_aprovacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppc',
            name='data_resolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppc',
            name='numero_processo_eletronico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número do processo eletrônico'),
        ),
        migrations.AddField(
            model_name='ppc',
            name='reitor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ppc',
            name='semestre_vigencia',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
        migrations.AddField(
            model_name='ppc',
            name='vice_reitor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
