# Generated by Django 6.0.7 on 2026-10-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0018_remove_grupoequivalenciacomponentes_matriz_final_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemequivalencia',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='itemequivalencia',
            constraint=models.UniqueConstraint(fields=('grupo', 'item_matriz'), name='uniq_item_equivalencia_grupo_item_matriz'),
        ),
        migrations.AddConstraint(
            model_name='itemequivalencia',
            constraint=models.UniqueConstraint(fields=('grupo', 'ordem'), name='uniq_item_equivalencia_grupo_ordem'),
        ),
    ]
