# Generated by Django 6.0.7 on 2026-10-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0019_alter_itemequivalencia_unique_together_and_more'),
    ]

