# Generated by Django 6.0.7 on 2026-10-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0020_remove_grupoequivalenciacomponentes_matriz_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apendice',
            name='tipo',
            field=models.CharField(choices=[('corpo_docente', 'Relação do corpo docente e titulação'), ('quadro_oferta', 'Quadro semestral de oferta de componentes curriculares'), ('estagio', 'Estágio'), ('tcc', 'Trabalho de Conclusão de Curso'), ('ac', 'Atividade Complementar')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalapendice',
            name='tipo',
            field=models.CharField(choices=[('corpo_docente', 'Relação do corpo docente e titulação'), ('quadro_oferta', 'Quadro semestral de oferta de componentes curriculares'), ('estagio', 'Estágio'), ('tcc', 'Trabalho de Conclusão de Curso'), ('ac', 'Atividade Complementar')], max_length=30),
        ),
    ]
