# Generated by Django 6.0.7 on 2026-10-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppc', '0021_remove_grupoequivalenciacomponentes_matriz_final_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='grupoequivalenciacomponentes',
                    name='matriz_final',
                ),
                migrations.RemoveField(
                    model_name='historicalgrupoequivalenciacomponentes',
                    name='matriz_final',
                ),
                migrations.AlterField(
                    model_name='componentecurricular',
                    name='ccu',
                    field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (None, 'Não sei'), (False, 'Não')], null=True, verbose_name='Esse componente é uma CCU?'),
                ),
                migrations.AlterField(
                    model_name='historicalcomponentecurricular',
                    name='ccu',
                    field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (None, 'Não sei'), (False, 'Não')], null=True, verbose_name='Esse componente é uma CCU?'),
                ),
            ],
            database_operations=[],  # vazio de propósito — não mexe no banco, só no "conhecimento" do Django
        ),
    ]
